import React from "react";
import { Svg, Rect, Line, Path, Text as SvgText } from "@react-pdf/renderer";
// eslint-disable-next-line @typescript-eslint/no-require-imports
const dagre = require("@dagrejs/dagre");

/**
 * Static data flow graph for PDF reports.
 *
 * Computes a left-to-right dagre layout server-side and emits @react-pdf
 * SVG primitives. Designed to be embedded inside a ContentPage in landscape
 * mode. Returns null if there's nothing to render.
 */

export interface PdfFlowAsset {
  id: string;
  name: string;
  type: string;
}

export interface PdfFlowEdge {
  sourceAssetId: string;
  destinationAssetId: string;
  isAutoGenerated?: boolean;
}

interface FlowGraphProps {
  assets: PdfFlowAsset[];
  flows: PdfFlowEdge[];
  width?: number;
  height?: number;
}

const NODE_W = 130;
const NODE_H = 38;
const PADDING = 12;

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + "…";
}

function typeLabel(t: string): string {
  return t.replace(/_/g, " ").toLowerCase();
}

export function FlowGraphSvg({ assets, flows, width = 780, height = 520 }: FlowGraphProps) {
  // Restrict to assets that participate in at least one flow
  const usedIds = new Set<string>();
  for (const f of flows) {
    usedIds.add(f.sourceAssetId);
    usedIds.add(f.destinationAssetId);
  }
  const usedAssets = assets.filter((a) => usedIds.has(a.id));
  if (usedAssets.length === 0 || flows.length === 0) return null;

  // Dagre layout
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const g: any = new dagre.graphlib.Graph();
  g.setGraph({ rankdir: "LR", nodesep: 24, ranksep: 70, marginx: PADDING, marginy: PADDING });
  g.setDefaultEdgeLabel(() => ({}));
  for (const a of usedAssets) {
    g.setNode(a.id, { width: NODE_W, height: NODE_H });
  }
  for (const f of flows) {
    if (usedIds.has(f.sourceAssetId) && usedIds.has(f.destinationAssetId)) {
      g.setEdge(f.sourceAssetId, f.destinationAssetId);
    }
  }
  dagre.layout(g);

  const positioned = usedAssets.map((a) => {
    const pos = g.node(a.id);
    return {
      ...a,
      x: pos.x - NODE_W / 2,
      y: pos.y - NODE_H / 2,
    };
  });
  const posMap = new Map(positioned.map((n) => [n.id, n]));

  // Total bounds
  const totalW = Math.max(...positioned.map((n) => n.x + NODE_W)) + PADDING;
  const totalH = Math.max(...positioned.map((n) => n.y + NODE_H)) + PADDING;

  return (
    <Svg width={width} height={height} viewBox={`0 0 ${totalW} ${totalH}`}>
      {/* Edges first so they sit behind nodes */}
      {flows.map((f, i) => {
        const src = posMap.get(f.sourceAssetId);
        const dst = posMap.get(f.destinationAssetId);
        if (!src || !dst) return null;

        const x1 = src.x + NODE_W;
        const y1 = src.y + NODE_H / 2;
        const x2 = dst.x;
        const y2 = dst.y + NODE_H / 2;

        // Arrowhead at destination
        const arrowSize = 5;
        const dx = x2 - x1;
        const dy = y2 - y1;
        const len = Math.sqrt(dx * dx + dy * dy) || 1;
        const ux = dx / len;
        const uy = dy / len;
        const ax = x2 - ux * arrowSize;
        const ay = y2 - uy * arrowSize;
        const px = -uy * (arrowSize / 2);
        const py = ux * (arrowSize / 2);
        const arrow = `M ${x2} ${y2} L ${ax + px} ${ay + py} L ${ax - px} ${ay - py} Z`;

        const stroke = f.isAutoGenerated ? "#9CA3AF" : "#4B5563";
        const dash = f.isAutoGenerated ? "2 2" : undefined;

        return (
          <React.Fragment key={`e-${i}`}>
            <Line
              x1={x1}
              y1={y1}
              x2={x2}
              y2={y2}
              stroke={stroke}
              strokeWidth={0.7}
              strokeDasharray={dash}
            />
            <Path d={arrow} fill={stroke} />
          </React.Fragment>
        );
      })}

      {/* Nodes on top */}
      {positioned.map((n) => (
        <React.Fragment key={n.id}>
          <Rect
            x={n.x}
            y={n.y}
            width={NODE_W}
            height={NODE_H}
            fill="#F9FAFB"
            stroke="#374151"
            strokeWidth={0.6}
          />
          <SvgText x={n.x + 6} y={n.y + 14} fill="#111827" style={{ fontSize: 7 }}>
            {truncate(n.name, 24)}
          </SvgText>
          <SvgText x={n.x + 6} y={n.y + 26} fill="#6B7280" style={{ fontSize: 5.5 }}>
            {truncate(typeLabel(n.type), 28)}
          </SvgText>
        </React.Fragment>
      ))}
    </Svg>
  );
}
