import prisma from "../src/lib/prisma";
import { renderToBuffer } from "@react-pdf/renderer";
import fs from "node:fs/promises";
import {
  DataInventoryReport,
  type DataInventoryExportData,
} from "../src/server/services/export/data-inventory-report";
import { ROPAReport } from "../src/server/services/export/ropa-report";
import type { ROPAEntry } from "../src/server/services/privacy/ropaGenerator";
import {
  renderFlowGraphPng,
  type PdfFlowAsset,
  type PdfFlowEdge,
  type PdfFlowCluster,
} from "../src/server/services/export/flow-graph-pdf";

const orgId = "cmnpflh5r000013q77ssfe148";

async function genDataInventory() {
  const org = await prisma.organization.findUniqueOrThrow({ where: { id: orgId } });
  const [assets, flows, transfers] = await Promise.all([
    prisma.dataAsset.findMany({
      where: { organizationId: orgId },
      include: { dataElements: true },
      orderBy: { name: "asc" },
    }),
    prisma.dataFlow.findMany({
      where: { organizationId: orgId },
      include: {
        sourceAsset: { select: { name: true } },
        destinationAsset: { select: { name: true } },
      },
      orderBy: { name: "asc" },
    }),
    prisma.dataTransfer.findMany({
      where: { organizationId: orgId },
      include: { processingActivity: { select: { name: true } } },
      orderBy: { name: "asc" },
    }),
  ]);

  const data: DataInventoryExportData = {
    assets: assets.map((a) => ({
      id: a.id,
      name: a.name,
      type: a.type,
      owner: a.owner,
      location: a.location,
      hostingType: a.hostingType,
      description: a.description,
      isProduction: a.isProduction,
      dataElements: a.dataElements.map((e) => ({
        name: e.name,
        category: e.category,
        sensitivity: e.sensitivity,
        isPersonalData: e.isPersonalData,
        isSpecialCategory: e.isSpecialCategory,
        retentionDays: e.retentionDays,
      })),
    })),
    flows: flows.map((f) => {
      const meta = f.metadata as { autoGenerated?: boolean } | null;
      return {
        name: f.name,
        description: f.description,
        sourceAssetId: f.sourceAssetId,
        destinationAssetId: f.destinationAssetId,
        sourceAsset: f.sourceAsset,
        destinationAsset: f.destinationAsset,
        dataCategories: f.dataCategories,
        frequency: f.frequency,
        encryptionMethod: f.encryptionMethod,
        isAutomated: f.isAutomated,
        isAutoGenerated: meta?.autoGenerated === true,
      };
    }),
    transfers: transfers.map((t) => ({
      name: t.name,
      destinationCountry: t.destinationCountry,
      destinationOrg: t.destinationOrg,
      mechanism: t.mechanism,
      safeguards: t.safeguards,
      tiaCompleted: t.tiaCompleted,
      tiaDate: t.tiaDate,
      isActive: t.isActive,
      processingActivity: t.processingActivity,
    })),
  };

  const flowGraph = await renderFlowGraphPng(
    data.assets.map((a) => ({ id: a.id, name: a.name, type: a.type })),
    data.flows.map((f) => ({
      sourceAssetId: f.sourceAssetId,
      destinationAssetId: f.destinationAssetId,
      label: [f.dataCategories[0], f.frequency].filter(Boolean).join(" · ") || undefined,
      isAutoGenerated: f.isAutoGenerated,
    })),
    { rankdir: "LR", fitWidth: 720 }
  );

  const buffer = await renderToBuffer(
    DataInventoryReport({ data, orgName: org.name, flowGraph })
  );
  await fs.writeFile("/tmp/conductrics-data-inventory.pdf", buffer);
  console.log("wrote /tmp/conductrics-data-inventory.pdf", buffer.length, "bytes");
}

async function genROPA() {
  const org = await prisma.organization.findUniqueOrThrow({ where: { id: orgId } });
  const activities = await prisma.processingActivity.findMany({
    where: { organizationId: orgId, isActive: true },
    include: {
      assets: {
        include: {
          linkedElements: { include: { dataElement: true } },
          dataAsset: { include: { dataElements: true } },
        },
      },
      transfers: true,
    },
    orderBy: { name: "asc" },
  });

  const entries: ROPAEntry[] = activities.map((activity) => ({
    name: activity.name,
    description: activity.description,
    purpose: activity.purpose,
    legalBasis: activity.legalBasis,
    legalBasisDetail: activity.legalBasisDetail,
    dataSubjects: activity.dataSubjects,
    dataCategories: activity.categories,
    recipients: activity.recipients,
    retentionPeriod: activity.retentionPeriod,
    automatedDecisionMaking: activity.automatedDecisionMaking,
    automatedDecisionDetail: activity.automatedDecisionDetail,
    systems: activity.assets.map((a) => {
      const effectiveElements =
        a.linkedElements.length > 0
          ? a.linkedElements.map((le) => le.dataElement)
          : a.dataAsset.dataElements;
      return {
        name: a.dataAsset.name,
        type: a.dataAsset.type,
        location: a.dataAsset.location,
        elements: effectiveElements.map((e) => ({
          name: e.name,
          category: e.category,
          sensitivity: e.sensitivity,
        })),
      };
    }),
    transfers: activity.transfers.map((t) => ({
      destination: t.destinationCountry,
      organization: t.destinationOrg,
      mechanism: t.mechanism,
      safeguards: t.safeguards,
    })),
    lastReviewed: activity.lastReviewedAt,
    nextReview: activity.nextReviewAt,
  }));

  const flows = await prisma.dataFlow.findMany({
    where: { organizationId: orgId },
    include: {
      sourceAsset: { select: { id: true, name: true, type: true } },
      destinationAsset: { select: { id: true, name: true, type: true } },
    },
  });

  const assetMap = new Map<string, PdfFlowAsset>();
  for (const a of activities) {
    for (const link of a.assets) {
      assetMap.set(link.dataAsset.id, {
        id: link.dataAsset.id,
        name: link.dataAsset.name,
        type: link.dataAsset.type,
      });
    }
  }
  for (const f of flows) {
    assetMap.set(f.sourceAsset.id, f.sourceAsset);
    assetMap.set(f.destinationAsset.id, f.destinationAsset);
  }

  const assetOwner = new Map<string, string>();
  for (const activity of [...activities].sort((a, b) => a.name.localeCompare(b.name))) {
    for (const link of activity.assets) {
      if (!assetOwner.has(link.dataAsset.id)) {
        assetOwner.set(link.dataAsset.id, activity.id);
      }
    }
  }

  const clusters: PdfFlowCluster[] = activities
    .map((a) => ({
      id: a.id,
      label: a.name,
      assetIds: a.assets
        .map((l) => l.dataAsset.id)
        .filter((id) => assetOwner.get(id) === a.id),
    }))
    .filter((c) => c.assetIds.length > 0);

  const flowEdges: PdfFlowEdge[] = flows.map((f) => {
    const meta = f.metadata as { autoGenerated?: boolean } | null;
    return {
      sourceAssetId: f.sourceAssetId,
      destinationAssetId: f.destinationAssetId,
      label: [f.dataCategories[0], f.frequency].filter(Boolean).join(" · ") || undefined,
      isAutoGenerated: meta?.autoGenerated === true,
    };
  });

  const flowGraph = await renderFlowGraphPng([...assetMap.values()], flowEdges, {
    rankdir: "LR",
    clusters,
    fitWidth: 720,
  });

  const buffer = await renderToBuffer(
    ROPAReport({ entries, orgName: org.name, flowGraph })
  );
  await fs.writeFile("/tmp/conductrics-ropa.pdf", buffer);
  console.log("wrote /tmp/conductrics-ropa.pdf", buffer.length, "bytes");
}

(async () => {
  await genDataInventory();
  await genROPA();
  await prisma.$disconnect();
})();
