"use client";

import { memo } from "react";
import {
  BaseEdge,
  EdgeLabelRenderer,
  getBezierPath,
  type EdgeProps,
  type Edge,
} from "@xyflow/react";
import type { FlowEdgeData } from "./useDataFlowGraph";

type FlowEdgeProps = EdgeProps<Edge<FlowEdgeData>>;

function FlowEdgeComponent({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  data,
  selected,
  style = {},
}: FlowEdgeProps) {
  const isReturn = data?.isReturn ?? false;
  const isBidirectional = data?.isBidirectional ?? false;
  const isAutoGenerated = data?.isAutoGenerated ?? false;

  // Separate bidirectional pairs via curvature: outbound curves up, return curves down
  const curvature = isReturn ? 0.5 : isBidirectional ? -0.5 : 0.25;

  const [edgePath, labelX, labelY] = getBezierPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
    curvature,
  });

  const flow = data?.flow;
  const categoryCount = flow?.dataCategories?.length || 0;
  const label = isBidirectional
    ? flow?.name || "Flow"
    : categoryCount > 0
      ? `${categoryCount} categories`
      : flow?.name || "Flow";

  return (
    <>
      <BaseEdge
        id={id}
        path={edgePath}
        style={{
          ...style,
          stroke: selected
            ? "hsl(var(--primary))"
            : isAutoGenerated
              ? "hsl(var(--primary) / 0.3)"
              : "hsl(var(--primary) / 0.5)",
          strokeWidth: selected ? 3 : isAutoGenerated ? 1.5 : 2,
          strokeDasharray: isReturn ? "6 3" : isAutoGenerated ? "2 3" : undefined,
        }}
        markerEnd="url(#arrowhead)"
      />
      <EdgeLabelRenderer>
        <div
          style={{
            position: "absolute",
            transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)`,
            pointerEvents: "all",
          }}
          className={`
            px-2 py-0.5 text-[10px] font-medium
            bg-background border border-border
            transition-all duration-200 cursor-pointer
            ${selected ? "border-primary text-primary" : "text-muted-foreground"}
          `}
        >
          {label}
        </div>
      </EdgeLabelRenderer>
    </>
  );
}

export const FlowEdge = memo(FlowEdgeComponent);
