"use client";
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 Rindogatan LLC

import { useTranslations } from "next-intl";
import { Filter, X, Eye, EyeOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { SENSITIVITY_COLOR, type Sensitivity } from "./flow-palette";

export type SensitivityFilter = Sensitivity | "all";

export interface FlowFilters {
  sensitivity: SensitivityFilter;
  showAutoGenerated: boolean;
  categories: Set<string>;
}

export const DEFAULT_FILTERS: FlowFilters = {
  sensitivity: "all",
  showAutoGenerated: true,
  categories: new Set(),
};

// Labels come from the shared `enums.dataCategory` namespace so the filter,
// the vendor badges and the forms can never drift apart.
const ALL_CATEGORIES: Array<{ key: string }> = [
  { key: "IDENTIFIERS" },
  { key: "DEMOGRAPHICS" },
  { key: "FINANCIAL" },
  { key: "HEALTH" },
  { key: "BIOMETRIC" },
  { key: "LOCATION" },
  { key: "BEHAVIORAL" },
  { key: "EMPLOYMENT" },
  { key: "EDUCATION" },
  { key: "POLITICAL" },
  { key: "RELIGIOUS" },
  { key: "GENETIC" },
  { key: "SEXUAL_ORIENTATION" },
  { key: "CRIMINAL" },
];

const SENSITIVITY_BUTTONS: Array<{
  key: SensitivityFilter;
  labelKey: "all" | "special" | "personal" | "general";
  swatch?: string;
}> = [
  { key: "all", labelKey: "all" },
  { key: "special", labelKey: "special", swatch: SENSITIVITY_COLOR.special.stroke },
  { key: "sensitive", labelKey: "personal", swatch: SENSITIVITY_COLOR.sensitive.stroke },
  { key: "general", labelKey: "general", swatch: SENSITIVITY_COLOR.general.stroke },
];

export function FlowFilterToolbar({
  filters,
  onChange,
  edgeCount,
  totalEdges,
}: {
  filters: FlowFilters;
  onChange: (next: FlowFilters) => void;
  edgeCount: number;
  totalEdges: number;
}) {
  const t = useTranslations("dataFlow");
  const tCategory = useTranslations("enums.dataCategory");

  const hasActiveFilters =
    filters.sensitivity !== "all" ||
    !filters.showAutoGenerated ||
    filters.categories.size > 0;

  return (
    <div
      className="flex items-center gap-2 shadow-sm px-2 py-1.5 text-xs"
      style={{
        backgroundColor: "#ffffff",
        border: "1px solid #e2e8f0",
        color: "#334155",
      }}
    >
      {/* Sensitivity filter pills */}
      <div className="flex items-center gap-1">
        {SENSITIVITY_BUTTONS.map((b) => {
          const active = filters.sensitivity === b.key;
          return (
            <button
              key={b.key}
              onClick={() => onChange({ ...filters, sensitivity: b.key })}
              className="flex items-center gap-1 px-2 py-1 font-semibold uppercase tracking-wider transition-colors"
              style={{
                fontSize: 10,
                letterSpacing: "0.06em",
                backgroundColor: active ? "#0f172a" : "#ffffff",
                color: active ? "#ffffff" : "#475569",
              }}
            >
              {b.swatch && (
                <span
                  className="inline-block w-2 h-2 shrink-0"
                  style={{ backgroundColor: b.swatch }}
                />
              )}
              {t(`filters.${b.labelKey}`)}
            </button>
          );
        })}
      </div>

      <div className="w-px h-5" style={{ backgroundColor: "#e2e8f0" }} aria-hidden />

      {/* Auto-generated toggle */}
      <button
        onClick={() =>
          onChange({ ...filters, showAutoGenerated: !filters.showAutoGenerated })
        }
        className="flex items-center gap-1.5 px-2 py-1 font-semibold uppercase tracking-wider transition-colors hover:bg-slate-100"
        style={{ fontSize: 10, letterSpacing: "0.06em", color: "#475569" }}
        title={
          filters.showAutoGenerated
            ? t("filters.hideAutoGenerated")
            : t("filters.showAutoGenerated")
        }
      >
        {filters.showAutoGenerated ? (
          <Eye className="w-3 h-3" />
        ) : (
          <EyeOff className="w-3 h-3" />
        )}
        {t("filters.autoGen")}
      </button>

      <div className="w-px h-5" style={{ backgroundColor: "#e2e8f0" }} aria-hidden />

      {/* Category multi-select */}
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            size="sm"
            className="h-7 text-xs gap-1.5 px-2 uppercase tracking-wider font-semibold hover:bg-slate-100"
            style={{ letterSpacing: "0.06em", color: "#475569" }}
          >
            <Filter className="w-3 h-3" />
            {t("filters.categories")}
            {filters.categories.size > 0 && (
              <span
                className="ml-1 inline-flex items-center justify-center min-w-4 h-4 px-1 text-[9px] font-bold"
                style={{ backgroundColor: "#0f172a", color: "#ffffff" }}
              >
                {filters.categories.size}
              </span>
            )}
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="start" className="max-h-80 overflow-y-auto">
          {ALL_CATEGORIES.map((c) => (
            <DropdownMenuCheckboxItem
              key={c.key}
              checked={filters.categories.has(c.key)}
              onCheckedChange={(checked) => {
                const next = new Set(filters.categories);
                if (checked) next.add(c.key);
                else next.delete(c.key);
                onChange({ ...filters, categories: next });
              }}
            >
              {tCategory(c.key as never)}
            </DropdownMenuCheckboxItem>
          ))}
          {filters.categories.size > 0 && (
            <>
              <DropdownMenuSeparator />
              <button
                onClick={() => onChange({ ...filters, categories: new Set() })}
                className="w-full text-left px-2 py-1.5 text-xs hover:bg-slate-100"
                style={{ color: "#64748b" }}
              >
                {t("filters.clearCategories")}
              </button>
            </>
          )}
        </DropdownMenuContent>
      </DropdownMenu>

      <div className="flex-1" />

      {/* Result counter + clear */}
      <span
        className="text-[10px] uppercase tracking-wider font-semibold"
        style={{ color: "#64748b" }}
      >
        {t("filters.flowCount", { shown: edgeCount, total: totalEdges })}
      </span>

      {hasActiveFilters && (
        <button
          onClick={() => onChange(DEFAULT_FILTERS)}
          className="flex items-center gap-1 px-1.5 py-0.5 transition-colors hover:bg-slate-100"
          style={{ color: "#64748b" }}
          title={t("filters.clearAll")}
        >
          <X className="w-3 h-3" />
        </button>
      )}
    </div>
  );
}
