import { getToken } from "next-auth/jwt";
import type { NextRequest } from "next/server";
import prisma from "@/lib/prisma";
import { renderToBuffer } from "@react-pdf/renderer";
import { DataInventoryReport, dataInventoryToCSV } from "@/server/services/export/data-inventory-report";
import type { DataInventoryExportData } from "@/server/services/export/data-inventory-report";
import { fmtDate } from "@/server/services/export/pdf-styles";
import { checkExportRateLimit, pdfErrorResponse } from "@/lib/api-export";
import { renderFlowGraphPng } from "@/server/services/export/flow-graph-pdf";

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const organizationId = searchParams.get("organizationId");
  const format = searchParams.get("format") || "pdf";

  if (!organizationId) {
    return Response.json({ error: "organizationId is required" }, { status: 400 });
  }

  const token = await getToken({ req: request as unknown as NextRequest });
  const userEmail = token?.email as string | undefined;
  if (!userEmail) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const limited = checkExportRateLimit(request, userEmail);
  if (limited) return limited;

  try {

  const membership = await prisma.organizationMember.findFirst({
    where: {
      organizationId,
      user: { email: userEmail },
    },
    include: { organization: true },
  });
  if (!membership) {
    return Response.json({ error: "Forbidden" }, { status: 403 });
  }

  const [assets, flows, transfers] = await Promise.all([
    prisma.dataAsset.findMany({
      where: { organizationId },
      include: { dataElements: true },
      orderBy: { name: "asc" },
    }),
    prisma.dataFlow.findMany({
      where: { organizationId },
      include: {
        sourceAsset: { select: { name: true } },
        destinationAsset: { select: { name: true } },
      },
      orderBy: { name: "asc" },
    }),
    prisma.dataTransfer.findMany({
      where: { organizationId },
      include: {
        processingActivity: { select: { name: true } },
      },
      orderBy: { name: "asc" },
    }),
  ]);

  const data: DataInventoryExportData = {
    assets: assets.map((a) => ({
      id: a.id,
      name: a.name,
      type: a.type,
      owner: a.owner,
      location: a.location,
      hostingType: a.hostingType,
      description: a.description,
      isProduction: a.isProduction,
      dataElements: a.dataElements.map((e) => ({
        name: e.name,
        category: e.category,
        sensitivity: e.sensitivity,
        isPersonalData: e.isPersonalData,
        isSpecialCategory: e.isSpecialCategory,
        retentionDays: e.retentionDays,
      })),
    })),
    flows: flows.map((f) => {
      const meta = f.metadata as { autoGenerated?: boolean } | null;
      return {
        name: f.name,
        description: f.description,
        sourceAssetId: f.sourceAssetId,
        destinationAssetId: f.destinationAssetId,
        sourceAsset: f.sourceAsset,
        destinationAsset: f.destinationAsset,
        dataCategories: f.dataCategories,
        frequency: f.frequency,
        encryptionMethod: f.encryptionMethod,
        isAutomated: f.isAutomated,
        isAutoGenerated: meta?.autoGenerated === true,
      };
    }),
    transfers: transfers.map((t) => ({
      name: t.name,
      destinationCountry: t.destinationCountry,
      destinationOrg: t.destinationOrg,
      mechanism: t.mechanism,
      safeguards: t.safeguards,
      tiaCompleted: t.tiaCompleted,
      tiaDate: t.tiaDate,
      isActive: t.isActive,
      processingActivity: t.processingActivity,
    })),
  };

  const orgName = membership.organization.name;
  const dateStr = fmtDate(new Date());

  // Audit log
  await prisma.auditLog.create({
    data: {
      organizationId,
      userId: membership.userId,
      entityType: "DataAsset",
      entityId: organizationId,
      action: "EXPORT_DATA_INVENTORY",
      changes: { format, assetCount: assets.length, flowCount: flows.length, transferCount: transfers.length },
    },
  });

  if (format === "csv") {
    const csv = dataInventoryToCSV(data);
    return new Response(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="Data-Inventory-${orgName.replace(/[^a-zA-Z0-9]/g, "-")}-${dateStr}.csv"`,
      },
    });
  }

  // Pre-render the data flow graph as a PNG so it can be embedded as an
  // <Image> in the React-PDF tree. Skipped automatically if there are no flows.
  const flowGraph = await renderFlowGraphPng(
    data.assets.map((a) => ({ id: a.id, name: a.name, type: a.type })),
    data.flows.map((f) => ({
      sourceAssetId: f.sourceAssetId,
      destinationAssetId: f.destinationAssetId,
      label: [f.dataCategories[0], f.frequency].filter(Boolean).join(" · ") || undefined,
      isAutoGenerated: f.isAutoGenerated,
    })),
    { rankdir: "LR", fitWidth: 720 }
  );

  const buffer = await renderToBuffer(
    DataInventoryReport({ data, orgName, flowGraph })
  );

  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="Data-Inventory-${orgName.replace(/[^a-zA-Z0-9]/g, "-")}-${dateStr}.pdf"`,
    },
  });
  } catch (err) {
    return pdfErrorResponse(err, "data-inventory");
  }
}
