export interface ExpertProfile {
  id: string;
  name: string;
  title: string;
  firm: string;
  bio: string;
  specializations: string[];
  languages: string[];
  location: { city: string; country: string };
  contactUrl: string;
  imageUrl?: string;
  certifications?: string[];
}

export const mockExperts: ExpertProfile[] = [
  {
    id: "exp-001",
    name: "Dr. Sophie Bergmann",
    title: "Partner, Data Protection",
    firm: "Bergmann & Associates",
    bio: "Over 15 years of experience advising multinational corporations on GDPR compliance, data protection impact assessments, and cross-border data transfers.",
    specializations: ["GDPR", "DPIA", "Cross-Border Transfers"],
    languages: ["English", "German", "French"],
    location: { city: "Berlin", country: "Germany" },
    contactUrl: "https://example.com/experts/sophie-bergmann",
    certifications: ["CIPP/E", "CIPM"],
  },
  {
    id: "exp-002",
    name: "James O'Sullivan",
    title: "Senior Privacy Counsel",
    firm: "DataShield Legal",
    bio: "Specializes in healthcare data privacy regulations including GDPR and national health data laws. Extensive experience with DPIAs for health-tech companies.",
    specializations: ["Healthcare", "GDPR", "DPIA"],
    languages: ["English", "Irish"],
    location: { city: "Dublin", country: "Ireland" },
    contactUrl: "https://example.com/experts/james-osullivan",
    certifications: ["CIPP/E", "HCISPP"],
  },
  {
    id: "exp-003",
    name: "Maria Gonzalez Torres",
    title: "Privacy Director",
    firm: "CyberPrivacy Consulting",
    bio: "Expert in vendor risk management and third-party data processing agreements. Helps organizations build robust vendor oversight programs.",
    specializations: ["Vendor Management", "Contracts", "GDPR"],
    languages: ["English", "Spanish", "Portuguese"],
    location: { city: "Madrid", country: "Spain" },
    contactUrl: "https://example.com/experts/maria-gonzalez",
    certifications: ["CIPP/E", "CIPT"],
  },
  {
    id: "exp-004",
    name: "Henrik Lindqvist",
    title: "Chief Privacy Officer",
    firm: "Nordic Privacy Group",
    bio: "Incident response specialist with deep experience in breach notification requirements across EU member states and coordination with data protection authorities.",
    specializations: ["Incident Response", "Breach Notification", "DPA Relations"],
    languages: ["English", "Swedish", "Norwegian"],
    location: { city: "Stockholm", country: "Sweden" },
    contactUrl: "https://example.com/experts/henrik-lindqvist",
    certifications: ["CIPP/E", "CISSP"],
  },
  {
    id: "exp-005",
    name: "Alessandra Ricci",
    title: "Privacy Counsel",
    firm: "Ricci & Partners",
    bio: "Focuses on data subject rights management and DSAR fulfillment processes. Advises on automated decision-making and profiling compliance.",
    specializations: ["DSAR", "Automated Decisions", "GDPR"],
    languages: ["English", "Italian"],
    location: { city: "Milan", country: "Italy" },
    contactUrl: "https://example.com/experts/alessandra-ricci",
    certifications: ["CIPP/E"],
  },
  {
    id: "exp-006",
    name: "Pierre Dumont",
    title: "Managing Partner",
    firm: "Dumont Privacy Law",
    bio: "Leading expert on French data protection law (CNIL guidance) and the interplay between GDPR and ePrivacy regulations.",
    specializations: ["GDPR", "ePrivacy", "Cookie Compliance"],
    languages: ["English", "French"],
    location: { city: "Paris", country: "France" },
    contactUrl: "https://example.com/experts/pierre-dumont",
    certifications: ["CIPP/E", "CIPM"],
  },
  {
    id: "exp-007",
    name: "Anna Kowalski",
    title: "Data Protection Consultant",
    firm: "PrivacyFirst Advisory",
    bio: "Specializes in privacy-by-design implementation for software companies. Experienced with Transfer Impact Assessments and Standard Contractual Clauses.",
    specializations: ["Privacy by Design", "TIA", "SCCs"],
    languages: ["English", "Polish", "German"],
    location: { city: "Warsaw", country: "Poland" },
    contactUrl: "https://example.com/experts/anna-kowalski",
    certifications: ["CIPP/E", "CIPT"],
  },
  {
    id: "exp-008",
    name: "Thomas van der Berg",
    title: "Senior Associate",
    firm: "Dutch Privacy Partners",
    bio: "Expert in financial services data protection, PSD2 compliance, and the intersection of privacy law with fintech regulations.",
    specializations: ["Financial Services", "Fintech", "GDPR"],
    languages: ["English", "Dutch"],
    location: { city: "Amsterdam", country: "Netherlands" },
    contactUrl: "https://example.com/experts/thomas-vanderberg",
    certifications: ["CIPP/E", "CISM"],
  },
  {
    id: "exp-009",
    name: "Elena Vasquez",
    title: "Privacy & Compliance Lead",
    firm: "TechPrivacy Solutions",
    bio: "Helps startups and scale-ups build privacy programs from scratch. Expertise in Records of Processing Activities (ROPA) and compliance frameworks.",
    specializations: ["ROPA", "Startup Privacy", "Compliance Frameworks"],
    languages: ["English", "Spanish"],
    location: { city: "Barcelona", country: "Spain" },
    contactUrl: "https://example.com/experts/elena-vasquez",
    certifications: ["CIPM", "ISO 27701 Lead Auditor"],
  },
  {
    id: "exp-010",
    name: "Dr. Marcus Weber",
    title: "Of Counsel",
    firm: "Weber Datenschutz",
    bio: "Academic turned practitioner with extensive experience in AI and data ethics, algorithmic accountability, and the EU AI Act's privacy implications.",
    specializations: ["AI Ethics", "EU AI Act", "GDPR"],
    languages: ["English", "German"],
    location: { city: "Munich", country: "Germany" },
    contactUrl: "https://example.com/experts/marcus-weber",
    certifications: ["CIPP/E", "CIPM", "CIPT"],
  },
  {
    id: "exp-011",
    name: "Fiona McCarthy",
    title: "Privacy Director",
    firm: "Atlantic Compliance Group",
    bio: "Specialist in children's data protection (Age Appropriate Design Code) and EdTech privacy requirements.",
    specializations: ["Children's Privacy", "EdTech", "GDPR"],
    languages: ["English"],
    location: { city: "London", country: "United Kingdom" },
    contactUrl: "https://example.com/experts/fiona-mccarthy",
    certifications: ["CIPP/E", "CIPM"],
  },
  {
    id: "exp-012",
    name: "Lukas Novak",
    title: "Senior Privacy Advisor",
    firm: "Central European Privacy Institute",
    bio: "Expert in multi-jurisdictional compliance across Central and Eastern Europe. Advises on national derogations from GDPR.",
    specializations: ["Multi-Jurisdictional", "National Derogations", "GDPR"],
    languages: ["English", "Czech", "Slovak", "German"],
    location: { city: "Prague", country: "Czech Republic" },
    contactUrl: "https://example.com/experts/lukas-novak",
    certifications: ["CIPP/E"],
  },
];

export const specializations = [
  "GDPR",
  "DPIA",
  "DSAR",
  "TIA",
  "Cross-Border Transfers",
  "Healthcare",
  "Financial Services",
  "Vendor Management",
  "Incident Response",
  "Breach Notification",
  "Privacy by Design",
  "AI Ethics",
  "ePrivacy",
  "Children's Privacy",
  "ROPA",
  "Compliance Frameworks",
];
