export interface ExpertProfile {
  id: string;
  name: string | null;
  email: string;
  title: string | null;
  firm: string | null;
  bio: string | null;
  expertType: "legal" | "technical" | "both";
  specializations: string[];
  certifications: string[];
  languages: string[]; // ISO 639-1
  location: { city: string | null; country: string | null }; // country = ISO 3166-1 alpha-2
  jurisdictions: string[];
  contactUrl: string | null;
  imageUrl?: string | null;
  acceptingClients: boolean;
  profileCompleteness: number; // 0–100
}

/** ISO 3166-1 alpha-2 → display name */
export const countryNames: Record<string, string> = {
  AT: "Austria",
  BE: "Belgium",
  CZ: "Czech Republic",
  DE: "Germany",
  DK: "Denmark",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GB: "United Kingdom",
  GR: "Greece",
  IE: "Ireland",
  IT: "Italy",
  NL: "Netherlands",
  NO: "Norway",
  PL: "Poland",
  PT: "Portugal",
  SE: "Sweden",
  CH: "Switzerland",
  US: "United States",
};

/** ISO 639-1 → display name */
export const languageNames: Record<string, string> = {
  cs: "Czech",
  da: "Danish",
  de: "German",
  el: "Greek",
  en: "English",
  es: "Spanish",
  fi: "Finnish",
  fr: "French",
  ga: "Irish",
  it: "Italian",
  nl: "Dutch",
  no: "Norwegian",
  pl: "Polish",
  pt: "Portuguese",
  sk: "Slovak",
  sv: "Swedish",
};

export const mockExperts: ExpertProfile[] = [
  {
    id: "exp-001",
    name: "Dr. Sophie Bergmann",
    email: "s.bergmann@bergmann-associates.de",
    title: "Partner, Data Protection",
    firm: "Bergmann & Associates",
    bio: "Over 15 years of experience advising multinational corporations on GDPR compliance, data protection impact assessments, and cross-border data transfers.",
    expertType: "legal",
    specializations: ["GDPR", "DPIA / Impact Assessments", "Cross-Border Transfers"],
    certifications: ["CIPP/E", "CIPM"],
    languages: ["en", "de", "fr"],
    location: { city: "Berlin", country: "DE" },
    jurisdictions: ["EU", "DE"],
    contactUrl: "https://example.com/experts/sophie-bergmann",
    acceptingClients: true,
    profileCompleteness: 95,
  },
  {
    id: "exp-002",
    name: "James O'Sullivan",
    email: "james@datashield.ie",
    title: "Senior Privacy Counsel",
    firm: "DataShield Legal",
    bio: "Specializes in healthcare data privacy regulations including GDPR and national health data laws. Extensive experience with DPIAs for health-tech companies.",
    expertType: "legal",
    specializations: ["Healthcare Privacy", "GDPR", "DPIA / Impact Assessments"],
    certifications: ["CIPP/E", "HCISPP"],
    languages: ["en", "ga"],
    location: { city: "Dublin", country: "IE" },
    jurisdictions: ["EU", "IE", "UK"],
    contactUrl: "https://example.com/experts/james-osullivan",
    acceptingClients: true,
    profileCompleteness: 88,
  },
  {
    id: "exp-003",
    name: "Maria Gonzalez Torres",
    email: "maria@cyberprivacy.es",
    title: "Privacy Director",
    firm: "CyberPrivacy Consulting",
    bio: "Expert in vendor risk management and third-party data processing agreements. Helps organizations build robust vendor oversight programs.",
    expertType: "both",
    specializations: ["Vendor Management", "Contracts & DPAs", "GDPR"],
    certifications: ["CIPP/E", "CIPT"],
    languages: ["en", "es", "pt"],
    location: { city: "Madrid", country: "ES" },
    jurisdictions: ["EU", "ES", "LATAM"],
    contactUrl: "https://example.com/experts/maria-gonzalez",
    acceptingClients: true,
    profileCompleteness: 92,
  },
  {
    id: "exp-004",
    name: "Henrik Lindqvist",
    email: "henrik@nordicprivacy.se",
    title: "Chief Privacy Officer",
    firm: "Nordic Privacy Group",
    bio: "Incident response specialist with deep experience in breach notification requirements across EU member states and coordination with data protection authorities.",
    expertType: "both",
    specializations: ["Incident Response", "Breach Notification", "DPA Relations"],
    certifications: ["CIPP/E", "CISSP"],
    languages: ["en", "sv", "no"],
    location: { city: "Stockholm", country: "SE" },
    jurisdictions: ["EU", "SE", "NO", "DK", "FI"],
    contactUrl: "https://example.com/experts/henrik-lindqvist",
    acceptingClients: false,
    profileCompleteness: 85,
  },
  {
    id: "exp-005",
    name: "Alessandra Ricci",
    email: "a.ricci@riccipartners.it",
    title: "Privacy Counsel",
    firm: "Ricci & Partners",
    bio: "Focuses on data subject rights management and DSAR fulfillment processes. Advises on automated decision-making and profiling compliance.",
    expertType: "legal",
    specializations: ["DSAR / Subject Rights", "Automated Decisions", "GDPR"],
    certifications: ["CIPP/E"],
    languages: ["en", "it"],
    location: { city: "Milan", country: "IT" },
    jurisdictions: ["EU", "IT"],
    contactUrl: "https://example.com/experts/alessandra-ricci",
    acceptingClients: true,
    profileCompleteness: 78,
  },
  {
    id: "exp-006",
    name: "Pierre Dumont",
    email: "pierre@dumont-privacy.fr",
    title: "Managing Partner",
    firm: "Dumont Privacy Law",
    bio: "Leading expert on French data protection law (CNIL guidance) and the interplay between GDPR and ePrivacy regulations.",
    expertType: "legal",
    specializations: ["GDPR", "ePrivacy / Cookies", "Cookie Compliance"],
    certifications: ["CIPP/E", "CIPM"],
    languages: ["en", "fr"],
    location: { city: "Paris", country: "FR" },
    jurisdictions: ["EU", "FR"],
    contactUrl: "https://example.com/experts/pierre-dumont",
    acceptingClients: true,
    profileCompleteness: 90,
  },
  {
    id: "exp-007",
    name: "Anna Kowalski",
    email: "anna@privacyfirst.pl",
    title: "Data Protection Consultant",
    firm: "PrivacyFirst Advisory",
    bio: "Specializes in privacy-by-design implementation for software companies. Experienced with Transfer Impact Assessments and Standard Contractual Clauses.",
    expertType: "technical",
    specializations: ["Privacy by Design", "TIA / Transfer Assessments", "SCCs"],
    certifications: ["CIPP/E", "CIPT"],
    languages: ["en", "pl", "de"],
    location: { city: "Warsaw", country: "PL" },
    jurisdictions: ["EU", "PL", "DE"],
    contactUrl: "https://example.com/experts/anna-kowalski",
    acceptingClients: true,
    profileCompleteness: 82,
  },
  {
    id: "exp-008",
    name: "Thomas van der Berg",
    email: "t.vanderberg@dutchprivacy.nl",
    title: "Senior Associate",
    firm: "Dutch Privacy Partners",
    bio: "Expert in financial services data protection, PSD2 compliance, and the intersection of privacy law with fintech regulations.",
    expertType: "legal",
    specializations: ["Financial Services", "Fintech Privacy", "GDPR"],
    certifications: ["CIPP/E", "CISM"],
    languages: ["en", "nl"],
    location: { city: "Amsterdam", country: "NL" },
    jurisdictions: ["EU", "NL"],
    contactUrl: "https://example.com/experts/thomas-vanderberg",
    acceptingClients: true,
    profileCompleteness: 87,
  },
  {
    id: "exp-009",
    name: "Elena Vasquez",
    email: "elena@techprivacy.es",
    title: "Privacy & Compliance Lead",
    firm: "TechPrivacy Solutions",
    bio: "Helps startups and scale-ups build privacy programs from scratch. Expertise in Records of Processing Activities (ROPA) and compliance frameworks.",
    expertType: "both",
    specializations: ["ROPA", "Startup Privacy", "Compliance Frameworks"],
    certifications: ["CIPM", "ISO 27701 Lead Auditor"],
    languages: ["en", "es"],
    location: { city: "Barcelona", country: "ES" },
    jurisdictions: ["EU", "ES"],
    contactUrl: "https://example.com/experts/elena-vasquez",
    acceptingClients: true,
    profileCompleteness: 80,
  },
  {
    id: "exp-010",
    name: "Dr. Marcus Weber",
    email: "m.weber@weber-datenschutz.de",
    title: "Of Counsel",
    firm: "Weber Datenschutz",
    bio: "Academic turned practitioner with extensive experience in AI and data ethics, algorithmic accountability, and the EU AI Act's privacy implications.",
    expertType: "both",
    specializations: ["AI & Data Ethics", "EU AI Act", "GDPR"],
    certifications: ["CIPP/E", "CIPM", "CIPT"],
    languages: ["en", "de"],
    location: { city: "Munich", country: "DE" },
    jurisdictions: ["EU", "DE"],
    contactUrl: "https://example.com/experts/marcus-weber",
    acceptingClients: false,
    profileCompleteness: 93,
  },
  {
    id: "exp-011",
    name: "Fiona McCarthy",
    email: "fiona@atlanticcompliance.co.uk",
    title: "Privacy Director",
    firm: "Atlantic Compliance Group",
    bio: "Specialist in children's data protection (Age Appropriate Design Code) and EdTech privacy requirements.",
    expertType: "legal",
    specializations: ["Children's Privacy", "EdTech Privacy", "GDPR"],
    certifications: ["CIPP/E", "CIPM"],
    languages: ["en"],
    location: { city: "London", country: "GB" },
    jurisdictions: ["UK", "EU"],
    contactUrl: "https://example.com/experts/fiona-mccarthy",
    acceptingClients: true,
    profileCompleteness: 86,
  },
  {
    id: "exp-012",
    name: "Lukas Novak",
    email: "lukas@cepi.cz",
    title: "Senior Privacy Advisor",
    firm: "Central European Privacy Institute",
    bio: "Expert in multi-jurisdictional compliance across Central and Eastern Europe. Advises on national derogations from GDPR.",
    expertType: "legal",
    specializations: ["Multi-Jurisdictional", "National Derogations", "GDPR"],
    certifications: ["CIPP/E"],
    languages: ["en", "cs", "sk", "de"],
    location: { city: "Prague", country: "CZ" },
    jurisdictions: ["EU", "CZ", "SK", "AT"],
    contactUrl: "https://example.com/experts/lukas-novak",
    acceptingClients: true,
    profileCompleteness: 75,
  },
];

export const specializations = [
  "GDPR",
  "DPIA / Impact Assessments",
  "DSAR / Subject Rights",
  "TIA / Transfer Assessments",
  "Cross-Border Transfers",
  "Healthcare Privacy",
  "Financial Services",
  "Vendor Management",
  "Contracts & DPAs",
  "Incident Response",
  "Breach Notification",
  "Privacy by Design",
  "AI & Data Ethics",
  "EU AI Act",
  "ePrivacy / Cookies",
  "Children's Privacy",
  "EdTech Privacy",
  "Fintech Privacy",
  "ROPA",
  "Compliance Frameworks",
  "SCCs",
  "Multi-Jurisdictional",
  "Startup Privacy",
  "DPA Relations",
  "Automated Decisions",
  "National Derogations",
];

export const expertTypes = [
  { value: "legal", label: "Legal" },
  { value: "technical", label: "Technical" },
  { value: "both", label: "Legal & Technical" },
] as const;
